# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295903aba0ba150b61edea01202b5c64042ed6e382fd980381ed59bff64694e43f4d2586e8447bde8a71ea9ef6e15c60a6d33428e6115b88c0444a84d3eae1f1

test:
  secret_key_base: 5d32754f986d65daf0fa69956410e6f96954fe44c71818781ff4b9cd278cd823c44fb75723899d92e7ff81272302d636dc979ef8cbd04f82c83545d2cdae22ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
